version: 1.0.{build}
image: Visual Studio 2017

install:
- ps: iwr https://raw.githubusercontent.com/dotnet/cli/release/2.1.3xx/scripts/obtain/dotnet-install.ps1 -outfile dotnet-install.ps1
- ps: .\dotnet-install.ps1 -Version 2.1.300 -InstallDir $env:ProgramFiles/dotnet
- cmd: choco install dotnet.script

build_script:
- cmd: >-
    cd build

    refreshenv

    dotnet script build.csx

artifacts:
- path: build\Artifacts\NuGet\*.nupkg
  name: NuGet Packages

test: off
environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    IS_SECURE_BUILDENVIRONMENT:
        secure: xU2zj54rFEPVqg/UuGU/DA==
    GITHUB_REPO_TOKEN:
        secure: AzNlvlKMzcoPNzawN3Hv48N6dzPa0N57HdFfAXP2cELBp9uiwJxtLdKWuDhZyf21
    NUGET_APIKEY:
        secure: 81vsB74sZV0IlV1Ru/qKPbaDS47lQ80aeOLWCPmlvak7O/RA9EqqFqWVxZFS0ora
    CHOCO_APIKEY:
        secure: scd8oB50KqKDRvt/+TSgUJavZzY39iqqa+1AZmj1CGue1/vjWJn6vIO4sMhN+d2l